# This is a basic workflow to help you get started with Actions

name: Docker Build User Mapping Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  USER_PERMISSIONS_OUTPUT_CMD: |
    set -e
    echo '!App dir permissions'
    ls -al /app
    echo '!Mounted dir permissions'
    ls -al /docker-build-args
    echo 'Running as user'
    whoami
    id -u
    echo 'Running as group'
    id -g
    echo '!Command dir permissions'
    ls -al /home/runner/work/_temp/_runner_file_commands/
  WRITE_PERMISSION_CHECK_CMD: |
    set -e
    echo '!Read the file added to the docker image: /app/660-user-owned-copied-into-docker-image.txt'
    cat /app/660-user-owned-copied-into-docker-image.txt
    echo '!Write to this file added to docker image as current user?'
    echo 'test' > /app/660-user-owned-copied-into-docker-image.txt
    echo '!Read the file mounted into the docker image: /docker-build-args/file-mounted-from-host.txt'
    cat /docker-build-args/file-mounted-from-host.txt
    echo '!Write to this file mounted into the docker image as current user?'
    echo 'test' > /docker-build-args/file-mounted-from-host.txt
  OUTPUT_PERMISSION_CHECK_CMD: |
    set -e
    echo '!attempt to set output for stage'
    echo 'key=value' > $GITHUB_OUTPUT

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-with-user-mapping:
    # This ensures that the user in the docker container matches
    # the UID and GUID of the user that is building the image
    name: Build with user mapping, run as container user
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image with user mapping
        run: |
          docker build \
            --build-arg USERID=$(id -u) \
            --build-arg GROUPID=$(id -g) \
            -t test-docker-image \
            -f ./docker-build-args/Dockerfile.with-user-mapping .

      - name: Run Docker container with user mapping
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image \
            /bin/bash -c "${{ env.USER_PERMISSIONS_OUTPUT_CMD }}"

      - name: Run WRITE_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image \
            /bin/bash -c "${{ env.WRITE_PERMISSION_CHECK_CMD }}"

      - name: Run OUTPUT_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image \
            /bin/bash -c "${{ env.OUTPUT_PERMISSION_CHECK_CMD }}"

  build-with-user-mapping-run-with-user-mapping:
    # This is redundant as the user mapping is done in the Dockerfile
    # so `docker run` will use the `USER` that was declared in the Dockerfile
    name: Build with user mapping, run with user mapping
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg USERID=$(id -u) \
            --build-arg GROUPID=$(id -g) \
            -t test-docker-image \
            -f ./docker-build-args/Dockerfile.with-user-mapping .

      - name: Run USER_PERMISSIONS_OUTPUT_CMD's
        if: always()
        run: |
          docker run \
            --user "$(id -u):$(id -g)" \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image \
            /bin/bash -c "${{ env.USER_PERMISSIONS_OUTPUT_CMD }}"

      - name: Run WRITE_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            --user "$(id -u):$(id -g)" \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image \
            /bin/bash -c "${{ env.WRITE_PERMISSION_CHECK_CMD }}"

      - name: Run OUTPUT_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            --user "$(id -u):$(id -g)" \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image \
            /bin/bash -c "${{ env.OUTPUT_PERMISSION_CHECK_CMD }}"

  build-without-user-mapping-run-with-user-mapping:
    name: Build without user mapping, run with user mapping
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            -t test-docker-image-without-user-mapping \
            -f ./docker-build-args/Dockerfile.without-user-mapping .

      - name: Run USER_PERMISSIONS_OUTPUT_CMD's
        if: always()
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.USER_PERMISSIONS_OUTPUT_CMD }}"

      - name: Run WRITE_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.WRITE_PERMISSION_CHECK_CMD }}"

      - name: Run OUTPUT_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.OUTPUT_PERMISSION_CHECK_CMD }}"

  build-as-without-mapping-run-without-mapping:
    name: Build as without mapping, run with without mapping
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            -t test-docker-image-without-user-mapping \
            -f ./docker-build-args/Dockerfile.with-user-mapping .

      - name: Run Docker container
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.USER_PERMISSIONS_OUTPUT_CMD }}"

      - name: Run WRITE_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.WRITE_PERMISSION_CHECK_CMD }}"

      - name: Run OUTPUT_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.OUTPUT_PERMISSION_CHECK_CMD }}"

  build-without-mapping-run-without-user-mapping-with-sudo:
    name: Build without mapping, run without user mapping, use sudo to write to GITHUB_OUTPUT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            -t test-docker-image-without-user-mapping \
            -f ./docker-build-args/Dockerfile.with-sudo .

      - name: Output to GITHUB_OUTPUT with sudo
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "echo 'key=value' > sudo $GITHUB_OUTPUT"

      - name: Run WRITE_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.WRITE_PERMISSION_CHECK_CMD }}"

      - name: Run OUTPUT_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.OUTPUT_PERMISSION_CHECK_CMD }}"

  no-user-mapping:
    name: No user mapping, build and run as root user
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image without user mapping
        run: |
          docker build \
            -t test-docker-image-without-user-mapping \
            -f ./docker-build-args/Dockerfile.without-user-mapping .

      - name: Run USER_PERMISSIONS_OUTPUT_CMD's
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.USER_PERMISSIONS_OUTPUT_CMD }}"

      - name: Run WRITE_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.WRITE_PERMISSION_CHECK_CMD }}"

      - name: Run OUTPUT_PERMISSION_CHECK_CMD
        if: always()
        run: |
          docker run \
            -v ${{ github.workspace }}/docker-build-args:/docker-build-args \
            -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
            test-docker-image-without-user-mapping \
            /bin/bash -c "${{ env.OUTPUT_PERMISSION_CHECK_CMD }}"
