name: lhr-vs-hosted

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      command: 
        type: string

permissions:
  contents: read

jobs:
  build-hosted-standard:
    runs-on: ubuntu-22.04
    steps:
      - name: Run a one-line script
        run: |
          echo $RUNNER_ENVIRONMENT
          ${{ inputs.command }}
          
  build-hosted-standard-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo $RUNNER_ENVIRONMENT
          ${{ inputs.command }}
  
